name: CI
permissions:
  contents: read
on:
  workflow_dispatch:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup database using docker
        run: |
          docker compose -f compose.yml up db -d
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Prepare Laravel Application
        run: |
          cp .env.development .env
          php artisan key:generate
          php artisan migrate --force -n
      - name: Run tests
        run: php artisan test
      - name: Check openapi.json file
        run: |
          php artisan scramble:analyze
          php artisan scramble:export --path=openapi-ci.json
          diff openapi.json openapi-ci.json